### ISSUE TITLE
Accountant: Add command fails to open editor

### ISSUE THREAD

**Issue by nvsnkv** [nvsnkv/flow2#4]
```
Unhandled exception. System.InvalidOperationException: Collection was not enumerated!
   at Flow.Domain.Common.Collections.EnumerableWithCount`1.get_Count() in C:\Users\nvsnk\sources\repos\flow2\src\l0\Flow.Domain.Common\Collections\EnumerableWithCount.cs:line 21
   at Flow.Hosts.Accountant.Cli.Commands.EditTransactionsCommand.Execute(AddTransactionsArgs args, CancellationToken ct) in C:\Users\nvsnk\sources\repos\flow2\src\l3\CommandLine\Flow.Hosts.Accountant.Cli\Commands\EditTransactionsCommand.cs:line 60
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in C:\Users\nvsnk\sources\repos\flow2\src\l3\CommandLine\Flow.Hosts.Accountant.Cli\Program.cs:line 33
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in C:\Users\nvsnk\sources\repos\flow2\src\l3\CommandLine\Flow.Hosts.Accountant.Cli\Program.cs:line 32
   at Program.<Main>(String[] args)
```

**Comment by nvsnkv** [comment]
original issue solved in b220d0c , but another exception appears:
```
Unhandled exception. System.IO.IOException: The process cannot access the file 'add.2022-01-03T22_18_09.edit-appended.csv' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at Flow.Hosts.Common.Commands.CommandBase.CreateReader(String input) in C:\Users\nvsnk\sources\repos\flow2\src\l3\CommandLine\Flow.Hosts.Common\Commands\CommandBase.cs:line 58
   at Flow.Hosts.Accountant.Cli.Commands.EditTransactionsCommand.Update(String interim, SupportedFormat format, CancellationToken ct, String errsPath, EnumerableWithCount`1 rejected) in C:\Users\nvsnk\sources\repos\flow2\src\l3\CommandLine\Flow.Hosts.Accountant.Cli\Commands\EditTransactionsCommand.cs:line 117
   at Flow.Hosts.Accountant.Cli.Commands.EditTransactionsCommand.Edit(Expression`1 conditions, SupportedFormat format, CancellationToken ct, String interim, String errsPath, EnumerableWithCount`1 rejected) in C:\Users\nvsnk\sources\repos\flow2\src\l3\CommandLine\Flow.Hosts.Accountant.Cli\Commands\EditTransactionsCommand.cs:line 110
   at Flow.Hosts.Accountant.Cli.Commands.EditTransactionsCommand.Execute(AddTransactionsArgs args, CancellationToken ct) in C:\Users\nvsnk\sources\repos\flow2\src\l3\CommandLine\Flow.Hosts.Accountant.Cli\Commands\EditTransactionsCommand.cs:line 60
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in C:\Users\nvsnk\sources\repos\flow2\src\l3\CommandLine\Flow.Hosts.Accountant.Cli\Program.cs:line 33
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in C:\Users\nvsnk\sources\repos\flow2\src\l3\CommandLine\Flow.Hosts.Accountant.Cli\Program.cs:line 32
```
